import { describe, it, expect } from 'vitest';
import { render, screen } from '@testing-library/react';
import { BriefCard } from '../brief-card';

const mockBrief = {
  summary: 'Patient presents with persistent headache for 3 days.',
  chiefComplaint: 'Headache',
  riskFlags: ['Chest pain reported', 'Shortness of breath'],
  vitalsToCheck: ['Blood Pressure', 'Heart Rate', 'Oxygen Saturation'],
  suggestedFollowups: [
    'Any history of migraines in the family?',
    'Have you taken any medication for the pain?',
  ],
  medicationsNote: 'Patient is currently on Metformin 500mg',
  icd10Hints: ['R51 - Headache', 'I10 - Essential Hypertension'],
};

describe('BriefCard', () => {
  // ─── Header ────────────────────────────────────────────────

  it('should render the clinical intake brief title', () => {
    render(<BriefCard brief={mockBrief} />);
    expect(screen.getByText('Clinical Intake Brief')).toBeInTheDocument();
  });

  it('should render the subtitle', () => {
    render(<BriefCard brief={mockBrief} />);
    expect(
      screen.getByText(/Generated by AyuTalk/),
    ).toBeInTheDocument();
  });

  // ─── Summary ───────────────────────────────────────────────

  it('should render the summary section', () => {
    render(<BriefCard brief={mockBrief} />);
    expect(screen.getByText('Summary')).toBeInTheDocument();
    expect(
      screen.getByText('Patient presents with persistent headache for 3 days.'),
    ).toBeInTheDocument();
  });

  // ─── Chief Complaint ───────────────────────────────────────

  it('should render the chief complaint', () => {
    render(<BriefCard brief={mockBrief} />);
    expect(screen.getByText('Chief Complaint')).toBeInTheDocument();
    expect(screen.getByText('Headache')).toBeInTheDocument();
  });

  // ─── Risk Flags ────────────────────────────────────────────

  it('should render risk flags section when flags exist', () => {
    render(<BriefCard brief={mockBrief} />);
    expect(screen.getByText('Risk Flags')).toBeInTheDocument();
  });

  it('should render all risk flags', () => {
    render(<BriefCard brief={mockBrief} />);
    expect(screen.getByText('Chest pain reported')).toBeInTheDocument();
    expect(screen.getByText('Shortness of breath')).toBeInTheDocument();
  });

  it('should provide a screen-reader prefix for risk flags', () => {
    render(<BriefCard brief={mockBrief} />);
    const prefixes = Array.from(document.querySelectorAll('.sr-only')).map(
      (el) => el.textContent,
    );
    expect(prefixes.filter((t) => t === 'Risk flag: ')).toHaveLength(
      mockBrief.riskFlags.length,
    );
  });

  it('should highlight risk flags in red', () => {
    render(<BriefCard brief={mockBrief} />);
    const riskFlag = screen.getByText('Risk Flags');
    expect(riskFlag.className).toContain('text-red-500');
  });

  it('should not render risk flags section when array is empty', () => {
    const noRisk = { ...mockBrief, riskFlags: [] };
    render(<BriefCard brief={noRisk} />);
    expect(screen.queryByText('Risk Flags')).not.toBeInTheDocument();
  });

  // ─── Vitals to Check ───────────────────────────────────────

  it('should render vitals section header', () => {
    render(<BriefCard brief={mockBrief} />);
    expect(screen.getByText('Vitals to Check')).toBeInTheDocument();
  });

  it('should render all vitals items', () => {
    render(<BriefCard brief={mockBrief} />);
    expect(screen.getByText('Blood Pressure')).toBeInTheDocument();
    expect(screen.getByText('Heart Rate')).toBeInTheDocument();
    expect(screen.getByText('Oxygen Saturation')).toBeInTheDocument();
  });

  // ─── ICD-10 Hints ──────────────────────────────────────────

  it('should render ICD-10 hints section', () => {
    render(<BriefCard brief={mockBrief} />);
    expect(screen.getByText('ICD-10 Hints')).toBeInTheDocument();
  });

  it('should render all ICD-10 hints', () => {
    render(<BriefCard brief={mockBrief} />);
    expect(
      screen.getByText('R51 - Headache'),
    ).toBeInTheDocument();
    expect(
      screen.getByText('I10 - Essential Hypertension'),
    ).toBeInTheDocument();
  });

  // ─── Medications Note ──────────────────────────────────────

  it('should render medications note section', () => {
    render(<BriefCard brief={mockBrief} />);
    expect(screen.getByText('Medications Note')).toBeInTheDocument();
  });

  it('should render the medications note text', () => {
    render(<BriefCard brief={mockBrief} />);
    expect(
      screen.getByText('Patient is currently on Metformin 500mg'),
    ).toBeInTheDocument();
  });

  // ─── Suggested Follow-ups ──────────────────────────────────

  it('should render suggested follow-ups section', () => {
    render(<BriefCard brief={mockBrief} />);
    expect(
      screen.getByText('Suggested Follow-ups for Doctor'),
    ).toBeInTheDocument();
  });

  it('should render all follow-up items', () => {
    render(<BriefCard brief={mockBrief} />);
    expect(
      screen.getByText('Any history of migraines in the family?'),
    ).toBeInTheDocument();
    expect(
      screen.getByText('Have you taken any medication for the pain?'),
    ).toBeInTheDocument();
  });

  it('should not render follow-ups section when array is empty', () => {
    const noFollowups = { ...mockBrief, suggestedFollowups: [] };
    render(<BriefCard brief={noFollowups} />);
    expect(
      screen.queryByText('Suggested Follow-ups for Doctor'),
    ).not.toBeInTheDocument();
  });

  // ─── Action Buttons ────────────────────────────────────────

  it('should render the Mark as Reviewed button', () => {
    render(<BriefCard brief={mockBrief} />);
    expect(
      screen.getByRole('button', { name: /mark as reviewed/i }),
    ).toBeInTheDocument();
  });

  it('should render the Edit button', () => {
    render(<BriefCard brief={mockBrief} />);
    expect(screen.getByRole('button', { name: /edit/i })).toBeInTheDocument();
  });

  it('should render the Export button', () => {
    render(<BriefCard brief={mockBrief} />);
    expect(
      screen.getByRole('button', { name: /export/i }),
    ).toBeInTheDocument();
  });

  // ─── className ─────────────────────────────────────────────

  it('should merge custom className', () => {
    const { container } = render(
      <BriefCard brief={mockBrief} className="my-custom-class" />,
    );
    // The className is applied to the outer wrapper div
    const wrapper = container.firstChild as HTMLElement;
    expect(wrapper.className).toContain('my-custom-class');
  });
});
